version: "3.9"

#name: &PROJECTNAME agent-zero

services:
  agent-zero-exe:
    container_name: agent-zero-exe
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        user_name: agent-zero
    ports:
      - "50022:22"
      - '${APP_PORT:-5001}:5001'
    volumes:
      - ./../:/home/agent-zero/

#    entrypoint: ["/bin/bash", "-c", "/home/agent-zero/docker/initialize.sh"]
    command: ["tail", "-f", "/dev/null"]