version: "3.9"

#name: &PROJECTNAME agent-zero

services:
  agent-zero-exe:
    container_name: agent-zero-exe
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        user_name: agent-zero
    ports:
      - "50173:5173"
      - "50174:5174"
      - "50022:22"
    volumes:
      - ./../:/home/agent-zero/

#    entrypoint: ["/bin/bash", "-c", "/home/agent-zero/docker/initialize.sh"]
